spring.application.name=Hardware
server.servlet.context-path=/Hardwares
server.port=8084

#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:8081/HardwaresDB
spring.datasource.username=postgres
spring.datasource.password=Akifbro@987
spring.datasource.driver-class-name = org.postgresql.Driver
spring.jpa.hibernate.ddl-auto= update
spring.jpa.show-sql=true

spring.security.user.name=akif
spring.security.user.password=1234

server.servlet.session.cookie.same-site=strict

